name: Release prepared merge

on:
  pull_request:
    types: [closed]
    paths:
      - .release-prepared.json

permissions: {}

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      actions: write
      contents: write
      id-token: write
    uses: three-cubes/tc-pipelines/.github/workflows/release-on-merge.yml@c8369630218e674bc994e11b8d311245a51a44f3
    with:
      merge-sha: ${{ github.event.pull_request.merge_commit_sha }}
      calver-pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
      version-file: ""
      release-title: 'three-cubes-fitness $VERSION'
      tag-message: 'three-cubes-fitness $VERSION'
      draft: false
      fan-out-command: ""
